name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      theirs: ${{ steps.changes.outputs.theirs }}
      others: ${{ steps.changes.outputs.others }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            theirs:
              - 'posts/${{ github.event.pull_request.user.login }}/**'
            others:
              - 'posts/!(${{ github.event.pull_request.user.login }}/**)/**'
  lint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.theirs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - run: npx --no-install markdownlint **/*.md
        working-directory: posts/${{ github.event.pull_request.user.login }}
  scope:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.others == 'true'
    steps:
      - name: Checking out of scope changes
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed("There are changes outside of the user's scope!")
  dry-run:
    runs-on: ubuntu-latest
    needs: changes
    outputs:
      result_summary_table_json: ${{ steps.dry-run.outputs.result_summary_table_json }}
    if: needs.changes.outputs.theirs == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Dry-run on dev.to for ${{ github.event.pull_request.user.login }}
        id: dry-run
        uses: cloudx-labs/publish-devto@main
        with:
          devto_key: ${{ secrets[format('devto_key_{0}', github.event.pull_request.user.login)] }}
          github_token: ${{ secrets.CI_PAT_TOKEN }}
          files: 'posts/${{ github.event.pull_request.user.login }}/**/*.md'
          dry_run: true
  result-comment:
    runs-on: ubuntu-latest
    needs: dry-run
#    env:
#      SUMMARY: ${{ fromJSON(needs.dry-run.outputs.result_summary_table_json).content }}
    steps:
      - name: Dry-run output comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          check-only-first-line: true
          comment: |
            Dry-run output:
            ```
            ${{ fromJSON(needs.dry-run.outputs.result_summary_table_json).content }}
            ```