name: "publish - pabloromeo"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
       - '.github/workflows/publish.yml'
       - 'posts/pabloromeo/**'

env:
  username: 'pabloromeo'

# -----------------------------------------------------------------------------
# No changes needed below this point
# -----------------------------------------------------------------------------
jobs:
  prepare:
    outputs:
      username: ${{ env.username }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  publish:
    uses: cloudx-labs/posts/.github/workflows/publish.yml@main
    needs: prepare
    with:
      username: ${{ needs.prepare.outputs.username }}
    secrets:
      devto_token: ${{ secrets[format('devto_key_{0}', needs.prepare.outputs.username)] }}
# -----------------------------------------------------------------------------
