name: "Publish - Pablo Romeo"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
       - 'posts/pabloromeo/**'

env:
  username: 'pabloromeo'

# -----------------------------------------------------------------------------
jobs:
  publish:
    uses: ./.github/workflows/publish.yml@main
    with:
      username: ${{ env.username }}
      devto_token: ${{ secrets[format('devto_key_{0}', env.username)] }}

#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@v2
#      - name: Publish articles on dev.to for ${{env.username}}
#        uses: sinedied/publish-devto@v2
#        with:
#          devto_key: ${{ secrets[format('devto_key_{0}', env.username)] }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: 'posts/${{env.username}}/**/*.md'
#          branch: main
#          conventional_commits: true
