name: "Sync - Pablo Romeo"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
       - 'posts/pabloromeo/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup
        id: setup
        run: echo '::set-output name=username::pabloromeo'
      - name: Publish
        uses: ./.github/workflows/publish.yml
        with:
          username: ${{ steps.setup.outputs.username }}
#        secrets:
#          devto_token: ${{ secrets[format('{0}_token', steps.setup.outputs.username)] }}
