name: "dev.to sync"
on:
  pull_request_review:
    types: [submitted]
    paths:
      - 'posts/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    #if: github.event.review.state == 'approved'
    steps:
      - name: Branch
        run: echo "branch = ${{ github.event.pull_request.head.ref }}"
      - name: PR Author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }}."
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Store publish timestamp
        # Hack to avoid: https://github.com/sinedied/publish-devto/issues/18
        run: date > posts/${{ github.event.pull_request.user.login }}/.published
      - name: Publish articles on dev.to for ${{ github.event.pull_request.user.login }}
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets[format('devto_key_{0}', github.event.pull_request.user.login)] }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'posts/${{ github.event.pull_request.user.login }}/**/*.md'
          # (Optional) The git branch to use. Default is 'main'.
          branch: ${{ github.event.pull_request.head.ref }}
          # (Optional) Use conventional commit messages. Default is false.
          # See https://www.conventionalcommits.org. 
          conventional_commits: true
