name: "Sync - Pablo Romeo"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
       - 'posts/pabloromeo/**'

jobs:
  prepare:
    id: prepare
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.setup.outputs.username }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup
        id: setup
        run: echo '::set-output name=username::pabloromeo'

  publish:
    needs: prepare
    uses: ./.github/workflows/publish.yml@main
    with:
      username: ${{ jobs.prepare.outputs.username }}
    secrets:
      devto_token: ${{ secrets[format('{0}_token', jobs.prepare.outputs.username)] }}
