name: dev.to sync
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'posts/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
      - name: Generate sync file
        # Workaround for: https://github.com/sinedied/publish-devto/issues/18
        run: |
          date > posts/${{ github.event.pull_request.user.login }}/.sync
          git add posts/${{ github.event.pull_request.user.login }}/.sync
      - name: Publish articles on dev.to for ${{ github.event.pull_request.user.login }}
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets[format('devto_key_{0}', github.event.pull_request.user.login)] }}
          github_token: ${{ secrets.CI_PAT_TOKEN }}
          files: 'posts/${{ github.event.pull_request.user.login }}/**/*.md'
          # (Optional) The git branch to use. Default is 'main'.
          branch: main
          # (Optional) Use conventional commit messages. Default is false.
          # See https://www.conventionalcommits.org.
          conventional_commits: true
