name: "validate"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'posts/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      theirs: ${{ steps.changes.outputs.theirs }}
      any: ${{ steps.changes.outputs.any }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            theirs:
              - 'posts/${{ github.event.pull_request.user.login }}/**'
            any:
              - 'posts/**'

  lint:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Markdown
        if: needs.changes.outputs.theirs == 'true'
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: 'posts/${{ github.event.pull_request.user.login }}/**/*.md'
  scope:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Checking out of scope changes
        if: needs.changes.outputs.any == 'true' && needs.changes.outputs.theirs == 'false'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed("There are changes outside of the user's scope!")
